[package]
name = "tasks"
version = "0.1.0"
authors = ["Rob Saunders <rob@wearebrandnew.com>"]

[dependencies]
restson = "^0.1"
serde = "^1.0"
serde_derive = "^1.0"

[[bin]]
name = "tasks"
doc = false
